plugins:
  - jekyll-paginate
  - jekyll-sitemap

#-------------------------------
# General Site Settings
title: Ahmed Bayugo Latifa
description: "Computer Science Student at the University of Energy and Natural Resources, Sunyani, Ghana. Passionate about machine learning and data science."
baseurl: "" # keep empty for a custom domain at the root
url: "https://ahmedlatifa.com" # your custom domain
author: Ahmed Bayugo Latifa

#-------------------------------
# About Section
# (Quoted because it contains HTML)
subtitle: 'Computer Science Student <span style="color:#38BDF8">& Aspiring Data Scientist</span>'
location: "Sunyani, Ghana"
resume_url: /docs/Resume_Ahmed_Latifa.pdf
avatar_image: /img/profile_picture.jpg

#-------------------------------
# Contact links
# linkedln: "https://www.linkedin.com/in/louis-ag/#" # Add your linkedln handle
# github: "https://github.com/asahad/#" # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false

#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/